<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Builder: /mnt/c/Users/abell/Documents/GitHub/NRE-Builder/src/Config/NREB_Config.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="content" id="content">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-12 panel " style="padding-bottom: 15px;">
                                <div style="margin-bottom: 15px;">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_55be27304aee4fac13a1eb8fc08f58b6.php">Config</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NREB_Config.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e_b___config_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">    #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">    #include &lt;string&gt;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="preprocessor">    #include &lt;vector&gt;</span></div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;<span class="preprocessor">    #include &lt;fstream&gt;</span></div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;<span class="preprocessor">    #include &lt;iostream&gt;</span></div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;<span class="preprocessor">    #include &lt;sstream&gt;</span></div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;</div><div class="line"><a name="l00022"></a><span class="lineno">   22</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e_b.php">NREB</a> {</div><div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_config.php">Config</a> {</div><div class="line"><a name="l00028"></a><span class="lineno">   28</span>&#160;</div><div class="line"><a name="l00033"></a><span class="lineno"><a class="line" href="class_n_r_e_b_1_1_config_1_1_config.php">   33</a></span>&#160;            <span class="keyword">class </span><a class="code" href="namespace_config.php">Config</a> {</div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;                <span class="keyword">private</span> :   <span class="comment">// Fields</span></div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;                    std::string compiler;</div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;                    std::string linker;</div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;                    std::string archiver;</div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;                    std::string cFlags;</div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;                    std::string ldFlags;</div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;                    std::string out;</div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;                    std::vector&lt;std::string&gt; includes;</div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;                    std::vector&lt;std::string&gt; libs;</div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;                    std::vector&lt;std::string&gt; libDirs;</div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;                    std::vector&lt;std::string&gt; excluded;</div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;</div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;                <span class="keyword">public</span> :   <span class="comment">// Methods</span></div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_b_1_1_config_1_1_config.php#a96e4b7a5d2aac72a5191b7e84cd2fde6">Config</a>() = <span class="keyword">delete</span>;</div><div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;</div><div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;                    <span class="comment">//## Copy Constructor ##//</span></div><div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_b_1_1_config_1_1_config.php#a96e4b7a5d2aac72a5191b7e84cd2fde6">Config</a>(<a class="code" href="namespace_config.php">Config</a> <span class="keyword">const</span>&amp; c) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;</div><div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160;                    <span class="comment">//## Move Constructor ##//</span></div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_b_1_1_config_1_1_config.php#a96e4b7a5d2aac72a5191b7e84cd2fde6">Config</a>(<a class="code" href="namespace_config.php">Config</a> &amp;&amp; c) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;</div><div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_b_1_1_config_1_1_config.php#a7c4fb34a9348b628431c32339e23aba6">~Config</a>() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00072"></a><span class="lineno">   72</span>&#160;</div><div class="line"><a name="l00073"></a><span class="lineno">   73</span>&#160;                    <span class="comment">//## Getter ##//</span></div><div class="line"><a name="l00077"></a><span class="lineno">   77</span>&#160;<span class="comment"></span>                        std::string <span class="keyword">const</span>&amp; <a class="code" href="class_n_r_e_b_1_1_config_1_1_config.php#affef9c78e2bca98d8c7cfc6d59b1fad9">getCompiler</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00081"></a><span class="lineno">   81</span>&#160;                        std::string <span class="keyword">const</span>&amp; <a class="code" href="class_n_r_e_b_1_1_config_1_1_config.php#aa48ad93e3e721205c9d6feeffb102eda">getLinker</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00085"></a><span class="lineno">   85</span>&#160;                        std::string <span class="keyword">const</span>&amp; <a class="code" href="class_n_r_e_b_1_1_config_1_1_config.php#a69e559ab291bca3247d420044bda1043">getArchiver</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00089"></a><span class="lineno">   89</span>&#160;                        std::string <span class="keyword">const</span>&amp; <a class="code" href="class_n_r_e_b_1_1_config_1_1_config.php#a323be43577c152f4aa1ccb9133f195a1">getCFlags</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00093"></a><span class="lineno">   93</span>&#160;                        std::string <span class="keyword">const</span>&amp; <a class="code" href="class_n_r_e_b_1_1_config_1_1_config.php#ae459ec68a230a671106f926cfd437948">getLdFlags</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00097"></a><span class="lineno">   97</span>&#160;                        std::string <span class="keyword">const</span>&amp; <a class="code" href="class_n_r_e_b_1_1_config_1_1_config.php#aee0e564aea1f62a9d1abc9d7e73ce07e">getOut</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00101"></a><span class="lineno">  101</span>&#160;                        std::vector&lt;std::string&gt; <span class="keyword">const</span>&amp; <a class="code" href="class_n_r_e_b_1_1_config_1_1_config.php#ab6d531d72529e32002eda38b03130925">getIncludes</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00105"></a><span class="lineno">  105</span>&#160;                        std::vector&lt;std::string&gt; <span class="keyword">const</span>&amp; <a class="code" href="class_n_r_e_b_1_1_config_1_1_config.php#af64eeadabcdf046a7219d024a0d97048">getLibs</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00109"></a><span class="lineno">  109</span>&#160;                        std::vector&lt;std::string&gt; <span class="keyword">const</span>&amp; <a class="code" href="class_n_r_e_b_1_1_config_1_1_config.php#a1cf890a75d1e53f1dfa34ee525a3cd1c">getLibDirs</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00113"></a><span class="lineno">  113</span>&#160;                        std::vector&lt;std::string&gt; <span class="keyword">const</span>&amp; <a class="code" href="class_n_r_e_b_1_1_config_1_1_config.php#ace05d08e52d31645a31205dd4b8a94b0">getExcluded</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00114"></a><span class="lineno">  114</span>&#160;</div><div class="line"><a name="l00115"></a><span class="lineno">  115</span>&#160;                    <span class="comment">//## Assignment Operator ##//</span></div><div class="line"><a name="l00121"></a><span class="lineno">  121</span>&#160;<span class="comment"></span>                        <a class="code" href="namespace_config.php">Config</a>&amp; <a class="code" href="class_n_r_e_b_1_1_config_1_1_config.php#a2cbe193896002017449d5dfd951ad4ad">operator =</a>(<a class="code" href="namespace_config.php">Config</a> <span class="keyword">const</span>&amp; c) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00127"></a><span class="lineno">  127</span>&#160;                        <a class="code" href="namespace_config.php">Config</a>&amp; <a class="code" href="class_n_r_e_b_1_1_config_1_1_config.php#a2cbe193896002017449d5dfd951ad4ad">operator =</a>(<a class="code" href="namespace_config.php">Config</a> &amp;&amp; c) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00128"></a><span class="lineno">  128</span>&#160;</div><div class="line"><a name="l00129"></a><span class="lineno">  129</span>&#160;                <span class="keyword">private</span> :    <span class="comment">// Methods</span></div><div class="line"><a name="l00134"></a><span class="lineno">  134</span>&#160;<span class="comment"></span>                    <a class="code" href="class_n_r_e_b_1_1_config_1_1_config.php#a96e4b7a5d2aac72a5191b7e84cd2fde6">Config</a>(std::string <span class="keyword">const</span>&amp; configPath);</div><div class="line"><a name="l00142"></a><span class="lineno">  142</span>&#160;                    <span class="keywordtype">void</span> removeTags(std::string&amp; includesLine, std::string&amp; libsLine, std::string&amp; libDirsLine, std::string&amp; excludedLine);</div><div class="line"><a name="l00143"></a><span class="lineno">  143</span>&#160;</div><div class="line"><a name="l00144"></a><span class="lineno">  144</span>&#160;                <span class="keyword">public</span> :     <span class="comment">// Static</span></div><div class="line"><a name="l00149"></a><span class="lineno">  149</span>&#160;<span class="comment"></span>                    <span class="keyword">static</span> <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_b_1_1_config_1_1_config.php#a96dc985640aaf39350eeeaca0ea0495f">setConfigPath</a>(std::string <span class="keyword">const</span>&amp; configPath);</div><div class="line"><a name="l00153"></a><span class="lineno">  153</span>&#160;                    <span class="keyword">static</span> <a class="code" href="namespace_config.php">Config</a> <span class="keyword">const</span>&amp; <a class="code" href="class_n_r_e_b_1_1_config_1_1_config.php#a84b2437b12ae2c467c6ffef2c345a808">getConfig</a>();</div><div class="line"><a name="l00154"></a><span class="lineno">  154</span>&#160;</div><div class="line"><a name="l00155"></a><span class="lineno">  155</span>&#160;                <span class="keyword">private</span> :    <span class="comment">// Static</span></div><div class="line"><a name="l00156"></a><span class="lineno">  156</span>&#160;                    <span class="keyword">static</span> std::string configFilePath;</div><div class="line"><a name="l00157"></a><span class="lineno">  157</span>&#160;</div><div class="line"><a name="l00158"></a><span class="lineno">  158</span>&#160;                <span class="keyword">public</span> :     <span class="comment">// Static</span></div><div class="line"><a name="l00159"></a><span class="lineno">  159</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string TAG_COMPILER;</div><div class="line"><a name="l00160"></a><span class="lineno">  160</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string TAG_LINKER;</div><div class="line"><a name="l00161"></a><span class="lineno">  161</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string TAG_ARCHIVER;</div><div class="line"><a name="l00162"></a><span class="lineno">  162</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string TAG_CFLAGS;</div><div class="line"><a name="l00163"></a><span class="lineno">  163</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string TAG_LDFLAGS;</div><div class="line"><a name="l00164"></a><span class="lineno">  164</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string TAG_INC;</div><div class="line"><a name="l00165"></a><span class="lineno">  165</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string TAG_LIB;</div><div class="line"><a name="l00166"></a><span class="lineno">  166</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string TAG_LIBDIR;</div><div class="line"><a name="l00167"></a><span class="lineno">  167</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string TAG_OUT;</div><div class="line"><a name="l00168"></a><span class="lineno">  168</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string TAG_EXCLUDED;</div><div class="line"><a name="l00169"></a><span class="lineno">  169</span>&#160;            };</div><div class="line"><a name="l00170"></a><span class="lineno">  170</span>&#160;        }</div><div class="line"><a name="l00171"></a><span class="lineno">  171</span>&#160;    }</div><div class="ttc" id="class_n_r_e_b_1_1_config_1_1_config_php_a1cf890a75d1e53f1dfa34ee525a3cd1c"><div class="ttname"><a href="class_n_r_e_b_1_1_config_1_1_config.php#a1cf890a75d1e53f1dfa34ee525a3cd1c">NREB::Config::Config::getLibDirs</a></div><div class="ttdeci">std::vector&lt; std::string &gt; const &amp; getLibDirs() const </div><div class="ttdef"><b>Definition:</b> NREB_Config.cpp:112</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_config_1_1_config_php_ae459ec68a230a671106f926cfd437948"><div class="ttname"><a href="class_n_r_e_b_1_1_config_1_1_config.php#ae459ec68a230a671106f926cfd437948">NREB::Config::Config::getLdFlags</a></div><div class="ttdeci">std::string const &amp; getLdFlags() const </div><div class="ttdef"><b>Definition:</b> NREB_Config.cpp:96</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_config_1_1_config_php_affef9c78e2bca98d8c7cfc6d59b1fad9"><div class="ttname"><a href="class_n_r_e_b_1_1_config_1_1_config.php#affef9c78e2bca98d8c7cfc6d59b1fad9">NREB::Config::Config::getCompiler</a></div><div class="ttdeci">std::string const &amp; getCompiler() const </div><div class="ttdef"><b>Definition:</b> NREB_Config.cpp:80</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_config_1_1_config_php_aee0e564aea1f62a9d1abc9d7e73ce07e"><div class="ttname"><a href="class_n_r_e_b_1_1_config_1_1_config.php#aee0e564aea1f62a9d1abc9d7e73ce07e">NREB::Config::Config::getOut</a></div><div class="ttdeci">std::string const &amp; getOut() const </div><div class="ttdef"><b>Definition:</b> NREB_Config.cpp:100</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_config_1_1_config_php_ab6d531d72529e32002eda38b03130925"><div class="ttname"><a href="class_n_r_e_b_1_1_config_1_1_config.php#ab6d531d72529e32002eda38b03130925">NREB::Config::Config::getIncludes</a></div><div class="ttdeci">std::vector&lt; std::string &gt; const &amp; getIncludes() const </div><div class="ttdef"><b>Definition:</b> NREB_Config.cpp:104</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_config_1_1_config_php_af64eeadabcdf046a7219d024a0d97048"><div class="ttname"><a href="class_n_r_e_b_1_1_config_1_1_config.php#af64eeadabcdf046a7219d024a0d97048">NREB::Config::Config::getLibs</a></div><div class="ttdeci">std::vector&lt; std::string &gt; const &amp; getLibs() const </div><div class="ttdef"><b>Definition:</b> NREB_Config.cpp:108</div></div>
<div class="ttc" id="namespace_config_php"><div class="ttname"><a href="namespace_config.php">Config</a></div><div class="ttdoc">Builder&amp;#39;s Configuration module. </div></div>
<div class="ttc" id="class_n_r_e_b_1_1_config_1_1_config_php_a2cbe193896002017449d5dfd951ad4ad"><div class="ttname"><a href="class_n_r_e_b_1_1_config_1_1_config.php#a2cbe193896002017449d5dfd951ad4ad">NREB::Config::Config::operator=</a></div><div class="ttdeci">Config &amp; operator=(Config const &amp;c)=delete</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_config_1_1_config_php_a96dc985640aaf39350eeeaca0ea0495f"><div class="ttname"><a href="class_n_r_e_b_1_1_config_1_1_config.php#a96dc985640aaf39350eeeaca0ea0495f">NREB::Config::Config::setConfigPath</a></div><div class="ttdeci">static void setConfigPath(std::string const &amp;configPath)</div><div class="ttdef"><b>Definition:</b> NREB_Config.cpp:120</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_config_1_1_config_php_aa48ad93e3e721205c9d6feeffb102eda"><div class="ttname"><a href="class_n_r_e_b_1_1_config_1_1_config.php#aa48ad93e3e721205c9d6feeffb102eda">NREB::Config::Config::getLinker</a></div><div class="ttdeci">std::string const &amp; getLinker() const </div><div class="ttdef"><b>Definition:</b> NREB_Config.cpp:84</div></div>
<div class="ttc" id="namespace_n_r_e_b_php"><div class="ttname"><a href="namespace_n_r_e_b.php">NREB</a></div><div class="ttdoc">The NRE-Builder global namespace. </div><div class="ttdef"><b>Definition:</b> NREB_Config.cpp:12</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_config_1_1_config_php_a7c4fb34a9348b628431c32339e23aba6"><div class="ttname"><a href="class_n_r_e_b_1_1_config_1_1_config.php#a7c4fb34a9348b628431c32339e23aba6">NREB::Config::Config::~Config</a></div><div class="ttdeci">~Config()=default</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_config_1_1_config_php_ace05d08e52d31645a31205dd4b8a94b0"><div class="ttname"><a href="class_n_r_e_b_1_1_config_1_1_config.php#ace05d08e52d31645a31205dd4b8a94b0">NREB::Config::Config::getExcluded</a></div><div class="ttdeci">std::vector&lt; std::string &gt; const &amp; getExcluded() const </div><div class="ttdef"><b>Definition:</b> NREB_Config.cpp:116</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_config_1_1_config_php_a323be43577c152f4aa1ccb9133f195a1"><div class="ttname"><a href="class_n_r_e_b_1_1_config_1_1_config.php#a323be43577c152f4aa1ccb9133f195a1">NREB::Config::Config::getCFlags</a></div><div class="ttdeci">std::string const &amp; getCFlags() const </div><div class="ttdef"><b>Definition:</b> NREB_Config.cpp:92</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_config_1_1_config_php_a96e4b7a5d2aac72a5191b7e84cd2fde6"><div class="ttname"><a href="class_n_r_e_b_1_1_config_1_1_config.php#a96e4b7a5d2aac72a5191b7e84cd2fde6">NREB::Config::Config::Config</a></div><div class="ttdeci">Config()=delete</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_config_1_1_config_php_a69e559ab291bca3247d420044bda1043"><div class="ttname"><a href="class_n_r_e_b_1_1_config_1_1_config.php#a69e559ab291bca3247d420044bda1043">NREB::Config::Config::getArchiver</a></div><div class="ttdeci">std::string const &amp; getArchiver() const </div><div class="ttdef"><b>Definition:</b> NREB_Config.cpp:88</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_config_1_1_config_php_a84b2437b12ae2c467c6ffef2c345a808"><div class="ttname"><a href="class_n_r_e_b_1_1_config_1_1_config.php#a84b2437b12ae2c467c6ffef2c345a808">NREB::Config::Config::getConfig</a></div><div class="ttdeci">static Config const &amp; getConfig()</div><div class="ttdef"><b>Definition:</b> NREB_Config.cpp:124</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</div>
</div>
</body>
</html>
