<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Builder: /mnt/c/Users/abell/Documents/GitHub/NRE-Builder/src/IO/NREB_Entry.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="content" id="content">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-12 panel " style="padding-bottom: 15px;">
                                <div style="margin-bottom: 15px;">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_fae119eb913a40fe8ed97cde8b98911e.php">IO</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NREB_Entry.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e_b___entry_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">    #include &lt;iostream&gt;</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;<span class="preprocessor">    #include &lt;string&gt;</span></div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">    #include &lt;algorithm&gt;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="preprocessor">    #include &lt;experimental/filesystem&gt;</span></div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;</div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;<span class="preprocessor">    #pragma once</span></div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;</div><div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e_b.php">NREB</a> {</div><div class="line"><a name="l00026"></a><span class="lineno">   26</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_i_o.php">IO</a> {</div><div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;</div><div class="line"><a name="l00032"></a><span class="lineno"><a class="line" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">   32</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">Entry</a> {</div><div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;                <span class="keyword">private</span> :   <span class="comment">// Fields</span></div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;                    std::string name;   </div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;                    <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">Entry</a>* parent;      </div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;                <span class="keyword">public</span>:     <span class="comment">// Methods</span></div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_entry.php#a7e00f70497859302b2a3b4219a642463">Entry</a>(std::string <span class="keyword">const</span>&amp; n, <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">Entry</a>* p = <span class="keyword">nullptr</span>);</div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;</div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;<span class="comment"></span>                        <span class="keyword">virtual</span> <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_entry.php#a1341296cad92611034593091b988edfa">~Entry</a>() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;</div><div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;                    <span class="comment">//## Methods ##//</span></div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;<span class="comment"></span>                        std::string <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_entry.php#af56ce86fad0cbbbd71a40d91485f0f21">getPath</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;                        std::string <span class="keyword">const</span>&amp; <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_entry.php#a9b11eca85c0a8b0753311ccb01ec5f93">getName</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;                        <span class="keyword">const</span> <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">Entry</a>* <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_entry.php#add028712312b67faee3c3eb55a1002d3">getParent</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00069"></a><span class="lineno">   69</span>&#160;                        <span class="keyword">virtual</span> <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_entry.php#aa6f6f349daae620809562993c23603e7">isFile</a>() <span class="keyword">const</span> = 0;</div><div class="line"><a name="l00073"></a><span class="lineno">   73</span>&#160;                        <span class="keyword">virtual</span> <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_entry.php#ae1344768dd2c9f6b177a2695de7c0db1">isFolder</a>() <span class="keyword">const</span> = 0;</div><div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;</div><div class="line"><a name="l00075"></a><span class="lineno">   75</span>&#160;                <span class="keyword">public</span>:     <span class="comment">// static const</span></div><div class="line"><a name="l00076"></a><span class="lineno">   76</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string MARKER_HEADER;</div><div class="line"><a name="l00077"></a><span class="lineno">   77</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string MARKER_COMPILER;</div><div class="line"><a name="l00078"></a><span class="lineno">   78</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string MARKER_LINKER;</div><div class="line"><a name="l00079"></a><span class="lineno">   79</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string MARKER_CFLAGS;</div><div class="line"><a name="l00080"></a><span class="lineno">   80</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string MARKER_LDFLAGS;</div><div class="line"><a name="l00081"></a><span class="lineno">   81</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string MARKER_INC;</div><div class="line"><a name="l00082"></a><span class="lineno">   82</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string MARKER_BIN;</div><div class="line"><a name="l00083"></a><span class="lineno">   83</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string MARKER_LIB;</div><div class="line"><a name="l00084"></a><span class="lineno">   84</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string MARKER_LIBDIR;</div><div class="line"><a name="l00085"></a><span class="lineno">   85</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string MARKER_CHILDS;</div><div class="line"><a name="l00086"></a><span class="lineno">   86</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string MARKER_OUT;</div><div class="line"><a name="l00087"></a><span class="lineno">   87</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string MARKER_TARGET;</div><div class="line"><a name="l00088"></a><span class="lineno">   88</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string MARKER_OBJ;</div><div class="line"><a name="l00089"></a><span class="lineno">   89</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string MARKER_SOURCE;</div><div class="line"><a name="l00090"></a><span class="lineno">   90</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string MARKER_SOURCE_C;</div><div class="line"><a name="l00091"></a><span class="lineno">   91</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string MARKER_HEADER_C;</div><div class="line"><a name="l00092"></a><span class="lineno">   92</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string MARKER_O;</div><div class="line"><a name="l00093"></a><span class="lineno">   93</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string MARKER_OBJDIR;</div><div class="line"><a name="l00094"></a><span class="lineno">   94</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string START_CALL;</div><div class="line"><a name="l00095"></a><span class="lineno">   95</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string END_CALL;</div><div class="line"><a name="l00096"></a><span class="lineno">   96</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string CALL_COMPILER;</div><div class="line"><a name="l00097"></a><span class="lineno">   97</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string CALL_CFLAGS;</div><div class="line"><a name="l00098"></a><span class="lineno">   98</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string CALL_INC;</div><div class="line"><a name="l00099"></a><span class="lineno">   99</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string CALL_OBJDIR;</div><div class="line"><a name="l00100"></a><span class="lineno">  100</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string CALL_OBJ;</div><div class="line"><a name="l00101"></a><span class="lineno">  101</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string MAKEFILE;</div><div class="line"><a name="l00102"></a><span class="lineno">  102</span>&#160;                    <span class="keyword">static</span> <span class="keyword">const</span> std::string ARCHIVER;</div><div class="line"><a name="l00103"></a><span class="lineno">  103</span>&#160;            };</div><div class="line"><a name="l00104"></a><span class="lineno">  104</span>&#160;</div><div class="line"><a name="l00105"></a><span class="lineno">  105</span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_b_1_1_i_o_1_1_file.php">File</a>;</div><div class="line"><a name="l00106"></a><span class="lineno">  106</span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">Folder</a>;</div><div class="line"><a name="l00107"></a><span class="lineno">  107</span>&#160;</div><div class="line"><a name="l00108"></a><span class="lineno">  108</span>&#160;            <span class="keyword">typedef</span> std::vector&lt;File*&gt;      FileList;</div><div class="line"><a name="l00109"></a><span class="lineno">  109</span>&#160;            <span class="keyword">typedef</span> std::vector&lt;Entry*&gt;     EntryList;</div><div class="line"><a name="l00110"></a><span class="lineno">  110</span>&#160;            <span class="keyword">typedef</span> std::vector&lt;Folder*&gt;    FolderList;</div><div class="line"><a name="l00111"></a><span class="lineno">  111</span>&#160;        }</div><div class="line"><a name="l00112"></a><span class="lineno">  112</span>&#160;    }</div><div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_entry_php_a9b11eca85c0a8b0753311ccb01ec5f93"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_entry.php#a9b11eca85c0a8b0753311ccb01ec5f93">NREB::IO::Entry::getName</a></div><div class="ttdeci">std::string const &amp; getName() const </div><div class="ttdef"><b>Definition:</b> NREB_Entry.cpp:50</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_entry_php_aa6f6f349daae620809562993c23603e7"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_entry.php#aa6f6f349daae620809562993c23603e7">NREB::IO::Entry::isFile</a></div><div class="ttdeci">virtual bool isFile() const =0</div></div>
<div class="ttc" id="namespace_i_o_php"><div class="ttname"><a href="namespace_i_o.php">IO</a></div><div class="ttdoc">Builder&amp;#39;s IO module. </div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_folder_php"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_folder.php">NREB::IO::Folder</a></div><div class="ttdoc">Represent a folder entry. </div><div class="ttdef"><b>Definition:</b> NREB_Folder.hpp:35</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_entry_php"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></div><div class="ttdoc">Represent a system entry. </div><div class="ttdef"><b>Definition:</b> NREB_Entry.hpp:32</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_entry_php_af56ce86fad0cbbbd71a40d91485f0f21"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_entry.php#af56ce86fad0cbbbd71a40d91485f0f21">NREB::IO::Entry::getPath</a></div><div class="ttdeci">std::string getPath() const </div><div class="ttdef"><b>Definition:</b> NREB_Entry.cpp:58</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_entry_php_ae1344768dd2c9f6b177a2695de7c0db1"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_entry.php#ae1344768dd2c9f6b177a2695de7c0db1">NREB::IO::Entry::isFolder</a></div><div class="ttdeci">virtual bool isFolder() const =0</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_entry_php_add028712312b67faee3c3eb55a1002d3"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_entry.php#add028712312b67faee3c3eb55a1002d3">NREB::IO::Entry::getParent</a></div><div class="ttdeci">const Entry * getParent() const </div><div class="ttdef"><b>Definition:</b> NREB_Entry.cpp:54</div></div>
<div class="ttc" id="namespace_n_r_e_b_php"><div class="ttname"><a href="namespace_n_r_e_b.php">NREB</a></div><div class="ttdoc">The NRE-Builder global namespace. </div><div class="ttdef"><b>Definition:</b> NREB_Config.cpp:12</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_entry_php_a1341296cad92611034593091b988edfa"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_entry.php#a1341296cad92611034593091b988edfa">NREB::IO::Entry::~Entry</a></div><div class="ttdeci">virtual ~Entry()=default</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_file_php"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_file.php">NREB::IO::File</a></div><div class="ttdoc">Represent a file entry. </div><div class="ttdef"><b>Definition:</b> NREB_File.hpp:29</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_entry_php_a7e00f70497859302b2a3b4219a642463"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_entry.php#a7e00f70497859302b2a3b4219a642463">NREB::IO::Entry::Entry</a></div><div class="ttdeci">Entry(std::string const &amp;n, Entry *p=nullptr)</div><div class="ttdef"><b>Definition:</b> NREB_Entry.cpp:42</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</div>
</div>
</body>
</html>
