<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Builder: /mnt/c/Users/abell/Documents/GitHub/NRE-Builder/src/IO/Folder/NREB_Folder.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_fae119eb913a40fe8ed97cde8b98911e.php">IO</a></li><li class="navelem"><a class="el" href="dir_fb763fa5026d8f0e72e42ba5f6cb3954.php">Folder</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NREB_Folder.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e_b___folder_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">    #include &lt;vector&gt;</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;<span class="preprocessor">    #include &lt;fstream&gt;</span></div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">    #include &lt;sstream&gt;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;</div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;<span class="preprocessor">    #include &quot;../NREB_Entry.hpp&quot;</span></div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;<span class="preprocessor">    #include &quot;../File/NREB_File.hpp&quot;</span></div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;<span class="preprocessor">    #include &quot;../../Config/NREB_Config.hpp&quot;</span></div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;</div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;<span class="preprocessor">    #pragma once</span></div><div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;</div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e_b.php">NREB</a> {</div><div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_i_o.php">IO</a> {</div><div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;</div><div class="line"><a name="l00035"></a><span class="lineno"><a class="line" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">   35</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">Folder</a> : <span class="keyword">public</span> <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">Entry</a> {</div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;                <span class="keyword">private</span> :   <span class="comment">// Fields</span></div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;                    EntryList childs;       </div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;                <span class="keyword">public</span>:     <span class="comment">// Methods</span></div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a200d09d5cafa5f42733e0fdab3e6fbfb">Folder</a>(std::string <span class="keyword">const</span>&amp; n, <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">Entry</a>* p = <span class="keyword">nullptr</span>);</div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;</div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;<span class="comment"></span>                         <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a11bb19b193b12f799278f26a3bfe941c">~Folder</a>();</div><div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;</div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;                    <span class="comment">//## Methods ##//</span></div><div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;<span class="comment"></span>                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a284ee03f746161b570ecf36f632dce71">analyse</a>();</div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a5db1368f10238a5465e81657470baa2a">createMakefile</a>(FileList&amp; files, FolderList&amp; folders, std::string <span class="keyword">const</span>&amp; src = <span class="stringliteral">&quot;src&quot;</span>) <span class="keyword">const</span>;</div><div class="line"><a name="l00072"></a><span class="lineno">   72</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a2f4e4f205ae80203fe344b249fcc3651">createProjectMakefile</a>(FileList&amp; files, FolderList&amp; folders, std::string <span class="keyword">const</span>&amp; src = <span class="stringliteral">&quot;src&quot;</span>) <span class="keyword">const</span>;</div><div class="line"><a name="l00077"></a><span class="lineno">   77</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#acc66991e9252d115771dc85b615412e0">createArchiverScript</a>(FileList&amp; files) <span class="keyword">const</span>;</div><div class="line"><a name="l00081"></a><span class="lineno">   81</span>&#160;                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a7ef2443cb0c7accc61a18a225f0ae1a5">hasFileChild</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00085"></a><span class="lineno">   85</span>&#160;                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#ab169a5723c98e38a28df20b70beabdae">hasFolderChild</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00089"></a><span class="lineno">   89</span>&#160;                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a3c666250bf38cc4924045de654b8a569">hasDeepSources</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00093"></a><span class="lineno">   93</span>&#160;                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#ac2debe1b29d81be9bd73adbee77aaced">isFile</a>() <span class="keyword">const override</span>;</div><div class="line"><a name="l00097"></a><span class="lineno">   97</span>&#160;                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a4116a6ce5749b71129dfe45dc7e1598f">isFolder</a>() <span class="keyword">const override</span>;</div><div class="line"><a name="l00101"></a><span class="lineno">  101</span>&#160;                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a42b295486bc89df18c9e45301a1368e9">notOnlyHeaders</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00106"></a><span class="lineno">  106</span>&#160;                        FileList <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#ac35d781c5612a55c4e6e60169d4b4a66">getSourceChild</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00111"></a><span class="lineno">  111</span>&#160;                        FileList <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a8b032189a00342609959b3d3b324f211">getHeaderChild</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00116"></a><span class="lineno">  116</span>&#160;                        FolderList <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a1f91de5890dd9f664b8a15be8797651d">getFolderChild</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00120"></a><span class="lineno">  120</span>&#160;                        std::string <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a877992cec520215b8a49c8557ef7e9f0">getBackwardPath</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00124"></a><span class="lineno">  124</span>&#160;                        std::string <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#afef675d6bab5cad8881255604b9cb857">getObjectPath</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00128"></a><span class="lineno">  128</span>&#160;                        std::string <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#ad2e11edc0714cac960d7737f6769030b">getUpperName</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00132"></a><span class="lineno">  132</span>&#160;                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a5d2cadc168a1866e66828126d86e9054">hasCppSource</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00136"></a><span class="lineno">  136</span>&#160;                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a353ff0cc1b8682c152efc6f3fb18a7eb">hasCppHeader</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00140"></a><span class="lineno">  140</span>&#160;                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a059761302da03e78c01d05e752cf8a50">hasCSource</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00144"></a><span class="lineno">  144</span>&#160;                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#ae8971cd745155563cdb37e259f605caf">hasCHeader</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00150"></a><span class="lineno">  150</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#aaa9b103009e579114d6b73afe9cad2e5">insertFileChilds</a>(std::ofstream&amp; file, FileList&amp; files) <span class="keyword">const</span>;</div><div class="line"><a name="l00156"></a><span class="lineno">  156</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a4717bec5aa946fe5ac7a0810ef18d9c1">insertFolderChilds</a>(std::ofstream&amp; file, FolderList&amp; folders) <span class="keyword">const</span>;</div><div class="line"><a name="l00163"></a><span class="lineno">  163</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a94c926fa65e9307bfa0957f17b442613">insertTarget</a>(std::ofstream&amp; file, <span class="keywordtype">bool</span> hasFolder, <span class="keywordtype">bool</span> hasFile) <span class="keyword">const</span>;</div><div class="line"><a name="l00168"></a><span class="lineno">  168</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#aeb585ed56b0025aeb6f0eff720db5e1e">insertFolderCalls</a>(std::ofstream&amp; file) <span class="keyword">const</span>;</div><div class="line"><a name="l00173"></a><span class="lineno">  173</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#abe7407396d7d848325b5d9f9ac870457">insertFileCall</a>(std::ofstream&amp; file) <span class="keyword">const</span>;</div><div class="line"><a name="l00179"></a><span class="lineno">  179</span>&#160;                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#aa93c5fb7382942b52ac2a4045a963346">isExcluded</a>(std::string <span class="keyword">const</span>&amp; path);</div><div class="line"><a name="l00180"></a><span class="lineno">  180</span>&#160;            };</div><div class="line"><a name="l00181"></a><span class="lineno">  181</span>&#160;        }</div><div class="line"><a name="l00182"></a><span class="lineno">  182</span>&#160;    }</div><div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_folder_php_a5db1368f10238a5465e81657470baa2a"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a5db1368f10238a5465e81657470baa2a">NREB::IO::Folder::createMakefile</a></div><div class="ttdeci">void createMakefile(FileList &amp;files, FolderList &amp;folders, std::string const &amp;src=&quot;src&quot;) const </div><div class="ttdef"><b>Definition:</b> NREB_Folder.cpp:35</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_folder_php_ac2debe1b29d81be9bd73adbee77aaced"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_folder.php#ac2debe1b29d81be9bd73adbee77aaced">NREB::IO::Folder::isFile</a></div><div class="ttdeci">bool isFile() const override</div><div class="ttdef"><b>Definition:</b> NREB_Folder.cpp:166</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_folder_php_ae8971cd745155563cdb37e259f605caf"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_folder.php#ae8971cd745155563cdb37e259f605caf">NREB::IO::Folder::hasCHeader</a></div><div class="ttdeci">bool hasCHeader() const </div><div class="ttdef"><b>Definition:</b> NREB_Folder.cpp:263</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_folder_php_a94c926fa65e9307bfa0957f17b442613"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a94c926fa65e9307bfa0957f17b442613">NREB::IO::Folder::insertTarget</a></div><div class="ttdeci">void insertTarget(std::ofstream &amp;file, bool hasFolder, bool hasFile) const </div><div class="ttdef"><b>Definition:</b> NREB_Folder.cpp:293</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_folder_php_a7ef2443cb0c7accc61a18a225f0ae1a5"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a7ef2443cb0c7accc61a18a225f0ae1a5">NREB::IO::Folder::hasFileChild</a></div><div class="ttdeci">bool hasFileChild() const </div><div class="ttdef"><b>Definition:</b> NREB_Folder.cpp:134</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_folder_php_aeb585ed56b0025aeb6f0eff720db5e1e"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_folder.php#aeb585ed56b0025aeb6f0eff720db5e1e">NREB::IO::Folder::insertFolderCalls</a></div><div class="ttdeci">void insertFolderCalls(std::ofstream &amp;file) const </div><div class="ttdef"><b>Definition:</b> NREB_Folder.cpp:304</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_folder_php_a353ff0cc1b8682c152efc6f3fb18a7eb"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a353ff0cc1b8682c152efc6f3fb18a7eb">NREB::IO::Folder::hasCppHeader</a></div><div class="ttdeci">bool hasCppHeader() const </div><div class="ttdef"><b>Definition:</b> NREB_Folder.cpp:243</div></div>
<div class="ttc" id="namespace_i_o_php"><div class="ttname"><a href="namespace_i_o.php">IO</a></div><div class="ttdoc">Builder&amp;#39;s IO module. </div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_folder_php_a42b295486bc89df18c9e45301a1368e9"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a42b295486bc89df18c9e45301a1368e9">NREB::IO::Folder::notOnlyHeaders</a></div><div class="ttdeci">bool notOnlyHeaders() const </div><div class="ttdef"><b>Definition:</b> NREB_Folder.cpp:174</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_folder_php_ac35d781c5612a55c4e6e60169d4b4a66"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_folder.php#ac35d781c5612a55c4e6e60169d4b4a66">NREB::IO::Folder::getSourceChild</a></div><div class="ttdeci">FileList getSourceChild() const </div><div class="ttdef"><b>Definition:</b> NREB_Folder.cpp:186</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_folder_php_aaa9b103009e579114d6b73afe9cad2e5"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_folder.php#aaa9b103009e579114d6b73afe9cad2e5">NREB::IO::Folder::insertFileChilds</a></div><div class="ttdeci">void insertFileChilds(std::ofstream &amp;file, FileList &amp;files) const </div><div class="ttdef"><b>Definition:</b> NREB_Folder.cpp:273</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_folder_php_a4717bec5aa946fe5ac7a0810ef18d9c1"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a4717bec5aa946fe5ac7a0810ef18d9c1">NREB::IO::Folder::insertFolderChilds</a></div><div class="ttdeci">void insertFolderChilds(std::ofstream &amp;file, FolderList &amp;folders) const </div><div class="ttdef"><b>Definition:</b> NREB_Folder.cpp:283</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_folder_php_a1f91de5890dd9f664b8a15be8797651d"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a1f91de5890dd9f664b8a15be8797651d">NREB::IO::Folder::getFolderChild</a></div><div class="ttdeci">FolderList getFolderChild() const </div><div class="ttdef"><b>Definition:</b> NREB_Folder.cpp:206</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_folder_php"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_folder.php">NREB::IO::Folder</a></div><div class="ttdoc">Represent a folder entry. </div><div class="ttdef"><b>Definition:</b> NREB_Folder.hpp:35</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_entry_php"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></div><div class="ttdoc">Represent a system entry. </div><div class="ttdef"><b>Definition:</b> NREB_Entry.hpp:32</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_folder_php_acc66991e9252d115771dc85b615412e0"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_folder.php#acc66991e9252d115771dc85b615412e0">NREB::IO::Folder::createArchiverScript</a></div><div class="ttdeci">void createArchiverScript(FileList &amp;files) const </div><div class="ttdef"><b>Definition:</b> NREB_Folder.cpp:111</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_folder_php_a8b032189a00342609959b3d3b324f211"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a8b032189a00342609959b3d3b324f211">NREB::IO::Folder::getHeaderChild</a></div><div class="ttdeci">FileList getHeaderChild() const </div><div class="ttdef"><b>Definition:</b> NREB_Folder.cpp:196</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_folder_php_a200d09d5cafa5f42733e0fdab3e6fbfb"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a200d09d5cafa5f42733e0fdab3e6fbfb">NREB::IO::Folder::Folder</a></div><div class="ttdeci">Folder(std::string const &amp;n, Entry *p=nullptr)</div><div class="ttdef"><b>Definition:</b> NREB_Folder.cpp:17</div></div>
<div class="ttc" id="namespace_n_r_e_b_php"><div class="ttname"><a href="namespace_n_r_e_b.php">NREB</a></div><div class="ttdoc">The NRE-Builder global namespace. </div><div class="ttdef"><b>Definition:</b> NREB_Config.cpp:12</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_folder_php_afef675d6bab5cad8881255604b9cb857"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_folder.php#afef675d6bab5cad8881255604b9cb857">NREB::IO::Folder::getObjectPath</a></div><div class="ttdeci">std::string getObjectPath() const </div><div class="ttdef"><b>Definition:</b> NREB_Folder.cpp:223</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_folder_php_a11bb19b193b12f799278f26a3bfe941c"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a11bb19b193b12f799278f26a3bfe941c">NREB::IO::Folder::~Folder</a></div><div class="ttdeci">~Folder()</div><div class="ttdef"><b>Definition:</b> NREB_Folder.cpp:29</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_folder_php_ad2e11edc0714cac960d7737f6769030b"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_folder.php#ad2e11edc0714cac960d7737f6769030b">NREB::IO::Folder::getUpperName</a></div><div class="ttdeci">std::string getUpperName() const </div><div class="ttdef"><b>Definition:</b> NREB_Folder.cpp:227</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_folder_php_ab169a5723c98e38a28df20b70beabdae"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_folder.php#ab169a5723c98e38a28df20b70beabdae">NREB::IO::Folder::hasFolderChild</a></div><div class="ttdeci">bool hasFolderChild() const </div><div class="ttdef"><b>Definition:</b> NREB_Folder.cpp:144</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_folder_php_abe7407396d7d848325b5d9f9ac870457"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_folder.php#abe7407396d7d848325b5d9f9ac870457">NREB::IO::Folder::insertFileCall</a></div><div class="ttdeci">void insertFileCall(std::ofstream &amp;file) const </div><div class="ttdef"><b>Definition:</b> NREB_Folder.cpp:314</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_folder_php_aa93c5fb7382942b52ac2a4045a963346"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_folder.php#aa93c5fb7382942b52ac2a4045a963346">NREB::IO::Folder::isExcluded</a></div><div class="ttdeci">bool isExcluded(std::string const &amp;path)</div><div class="ttdef"><b>Definition:</b> NREB_Folder.cpp:331</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_folder_php_a4116a6ce5749b71129dfe45dc7e1598f"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a4116a6ce5749b71129dfe45dc7e1598f">NREB::IO::Folder::isFolder</a></div><div class="ttdeci">bool isFolder() const override</div><div class="ttdef"><b>Definition:</b> NREB_Folder.cpp:170</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_folder_php_a059761302da03e78c01d05e752cf8a50"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a059761302da03e78c01d05e752cf8a50">NREB::IO::Folder::hasCSource</a></div><div class="ttdeci">bool hasCSource() const </div><div class="ttdef"><b>Definition:</b> NREB_Folder.cpp:253</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_folder_php_a5d2cadc168a1866e66828126d86e9054"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a5d2cadc168a1866e66828126d86e9054">NREB::IO::Folder::hasCppSource</a></div><div class="ttdeci">bool hasCppSource() const </div><div class="ttdef"><b>Definition:</b> NREB_Folder.cpp:233</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_folder_php_a3c666250bf38cc4924045de654b8a569"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a3c666250bf38cc4924045de654b8a569">NREB::IO::Folder::hasDeepSources</a></div><div class="ttdeci">bool hasDeepSources() const </div><div class="ttdef"><b>Definition:</b> NREB_Folder.cpp:154</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_folder_php_a877992cec520215b8a49c8557ef7e9f0"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a877992cec520215b8a49c8557ef7e9f0">NREB::IO::Folder::getBackwardPath</a></div><div class="ttdeci">std::string getBackwardPath() const </div><div class="ttdef"><b>Definition:</b> NREB_Folder.cpp:216</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_folder_php_a2f4e4f205ae80203fe344b249fcc3651"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a2f4e4f205ae80203fe344b249fcc3651">NREB::IO::Folder::createProjectMakefile</a></div><div class="ttdeci">void createProjectMakefile(FileList &amp;files, FolderList &amp;folders, std::string const &amp;src=&quot;src&quot;) const </div><div class="ttdef"><b>Definition:</b> NREB_Folder.cpp:59</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_folder_php_a284ee03f746161b570ecf36f632dce71"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a284ee03f746161b570ecf36f632dce71">NREB::IO::Folder::analyse</a></div><div class="ttdeci">void analyse()</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
