<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Builder: /mnt/c/Users/abell/Documents/GitHub/NRE-Builder/src/IO/File/NREB_File.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="content" id="content">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-12 panel " style="padding-bottom: 15px;">
                                <div style="margin-bottom: 15px;">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_fae119eb913a40fe8ed97cde8b98911e.php">IO</a></li><li class="navelem"><a class="el" href="dir_8c2d54daae461503333d1cbd1fcf808f.php">File</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NREB_File.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e_b___file_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">    #include &quot;../NREB_Entry.hpp&quot;</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">    #pragma once</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;</div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e_b.php">NREB</a> {</div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_i_o.php">IO</a> {</div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;</div><div class="line"><a name="l00029"></a><span class="lineno"><a class="line" href="class_n_r_e_b_1_1_i_o_1_1_file.php">   29</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_b_1_1_i_o_1_1_file.php">File</a> : <span class="keyword">public</span> <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">Entry</a> {</div><div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;                <span class="keyword">private</span> :   <span class="comment">// Fields</span></div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;</div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;                <span class="keyword">public</span>:     <span class="comment">// Methods</span></div><div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_file.php#a7723d9abedcf87e276a3e85955d87e40">File</a>(std::string <span class="keyword">const</span>&amp; n, <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">Entry</a>* p = <span class="keyword">nullptr</span>);</div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;</div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;<span class="comment"></span>                         <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_file.php#ae056d8317b104e259ef97fc93e58f37d">~File</a>() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;</div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;                    <span class="comment">//## Methods ##//</span></div><div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;<span class="comment"></span>                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_file.php#a9b9461e0a9337af21e0fb3d9019025c2">isFile</a>() <span class="keyword">const override</span>;</div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_file.php#a9d0017942f8bf285e71a8399925e2ebd">isFolder</a>() <span class="keyword">const override</span>;</div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;                        std::string <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_file.php#a06449f6aa77b4a4875ea4fc3abbc5c58">getObjectName</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;                        std::string <a class="code" href="class_n_r_e_b_1_1_i_o_1_1_file.php#a00521e404b437a8046c8fca78754fcb3">getObjectPath</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;            };</div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;        }</div><div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;    }</div><div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_file_php_a9d0017942f8bf285e71a8399925e2ebd"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_file.php#a9d0017942f8bf285e71a8399925e2ebd">NREB::IO::File::isFolder</a></div><div class="ttdeci">bool isFolder() const override</div><div class="ttdef"><b>Definition:</b> NREB_File.cpp:22</div></div>
<div class="ttc" id="namespace_i_o_php"><div class="ttname"><a href="namespace_i_o.php">IO</a></div><div class="ttdoc">Builder&amp;#39;s IO module. </div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_entry_php"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></div><div class="ttdoc">Represent a system entry. </div><div class="ttdef"><b>Definition:</b> NREB_Entry.hpp:32</div></div>
<div class="ttc" id="namespace_n_r_e_b_php"><div class="ttname"><a href="namespace_n_r_e_b.php">NREB</a></div><div class="ttdoc">The NRE-Builder global namespace. </div><div class="ttdef"><b>Definition:</b> NREB_Config.cpp:12</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_file_php_a00521e404b437a8046c8fca78754fcb3"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_file.php#a00521e404b437a8046c8fca78754fcb3">NREB::IO::File::getObjectPath</a></div><div class="ttdeci">std::string getObjectPath() const </div><div class="ttdef"><b>Definition:</b> NREB_File.cpp:42</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_file_php"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_file.php">NREB::IO::File</a></div><div class="ttdoc">Represent a file entry. </div><div class="ttdef"><b>Definition:</b> NREB_File.hpp:29</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_file_php_a9b9461e0a9337af21e0fb3d9019025c2"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_file.php#a9b9461e0a9337af21e0fb3d9019025c2">NREB::IO::File::isFile</a></div><div class="ttdeci">bool isFile() const override</div><div class="ttdef"><b>Definition:</b> NREB_File.cpp:18</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_file_php_a06449f6aa77b4a4875ea4fc3abbc5c58"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_file.php#a06449f6aa77b4a4875ea4fc3abbc5c58">NREB::IO::File::getObjectName</a></div><div class="ttdeci">std::string getObjectName() const </div><div class="ttdef"><b>Definition:</b> NREB_File.cpp:26</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_file_php_ae056d8317b104e259ef97fc93e58f37d"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_file.php#ae056d8317b104e259ef97fc93e58f37d">NREB::IO::File::~File</a></div><div class="ttdeci">~File()=default</div></div>
<div class="ttc" id="class_n_r_e_b_1_1_i_o_1_1_file_php_a7723d9abedcf87e276a3e85955d87e40"><div class="ttname"><a href="class_n_r_e_b_1_1_i_o_1_1_file.php#a7723d9abedcf87e276a3e85955d87e40">NREB::IO::File::File</a></div><div class="ttdeci">File(std::string const &amp;n, Entry *p=nullptr)</div><div class="ttdef"><b>Definition:</b> NREB_File.cpp:15</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</div>
</div>
</body>
</html>
