<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Builder: NREB::Config::Config Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e_b.php">NREB</a></li><li class="navelem"><b>Config</b></li><li class="navelem"><a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php">Config</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-static-methods">Static Public Member Functions</a> &#124;
<a href="#pub-static-attribs">Static Public Attributes</a> &#124;
<a href="class_n_r_e_b_1_1_config_1_1_config-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NREB::Config::Config Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Represent the analyser configuration.  
 <a href="class_n_r_e_b_1_1_config_1_1_config.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e_b___config_8hpp_source.php">NREB_Config.hpp</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a96e4b7a5d2aac72a5191b7e84cd2fde6"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#a96e4b7a5d2aac72a5191b7e84cd2fde6">Config</a> ()=delete</td></tr>
<tr class="separator:a96e4b7a5d2aac72a5191b7e84cd2fde6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af208b04fe1dfbf205e56a6615f805d85"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#af208b04fe1dfbf205e56a6615f805d85">Config</a> (<a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php">Config</a> const &amp;c)=delete</td></tr>
<tr class="separator:af208b04fe1dfbf205e56a6615f805d85"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1f2fd0065cb47c13419ceb140c4d3f23"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#a1f2fd0065cb47c13419ceb140c4d3f23">Config</a> (<a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php">Config</a> &amp;&amp;c)=delete</td></tr>
<tr class="separator:a1f2fd0065cb47c13419ceb140c4d3f23"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7c4fb34a9348b628431c32339e23aba6"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#a7c4fb34a9348b628431c32339e23aba6">~Config</a> ()=default</td></tr>
<tr class="separator:a7c4fb34a9348b628431c32339e23aba6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:affef9c78e2bca98d8c7cfc6d59b1fad9"><td class="memItemLeft" align="right" valign="top">std::string const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#affef9c78e2bca98d8c7cfc6d59b1fad9">getCompiler</a> () const </td></tr>
<tr class="separator:affef9c78e2bca98d8c7cfc6d59b1fad9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa48ad93e3e721205c9d6feeffb102eda"><td class="memItemLeft" align="right" valign="top">std::string const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#aa48ad93e3e721205c9d6feeffb102eda">getLinker</a> () const </td></tr>
<tr class="separator:aa48ad93e3e721205c9d6feeffb102eda"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a69e559ab291bca3247d420044bda1043"><td class="memItemLeft" align="right" valign="top">std::string const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#a69e559ab291bca3247d420044bda1043">getArchiver</a> () const </td></tr>
<tr class="separator:a69e559ab291bca3247d420044bda1043"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a323be43577c152f4aa1ccb9133f195a1"><td class="memItemLeft" align="right" valign="top">std::string const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#a323be43577c152f4aa1ccb9133f195a1">getCFlags</a> () const </td></tr>
<tr class="separator:a323be43577c152f4aa1ccb9133f195a1"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae459ec68a230a671106f926cfd437948"><td class="memItemLeft" align="right" valign="top">std::string const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#ae459ec68a230a671106f926cfd437948">getLdFlags</a> () const </td></tr>
<tr class="separator:ae459ec68a230a671106f926cfd437948"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aee0e564aea1f62a9d1abc9d7e73ce07e"><td class="memItemLeft" align="right" valign="top">std::string const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#aee0e564aea1f62a9d1abc9d7e73ce07e">getOut</a> () const </td></tr>
<tr class="separator:aee0e564aea1f62a9d1abc9d7e73ce07e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab6d531d72529e32002eda38b03130925"><td class="memItemLeft" align="right" valign="top">std::vector&lt; std::string &gt; const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#ab6d531d72529e32002eda38b03130925">getIncludes</a> () const </td></tr>
<tr class="separator:ab6d531d72529e32002eda38b03130925"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af64eeadabcdf046a7219d024a0d97048"><td class="memItemLeft" align="right" valign="top">std::vector&lt; std::string &gt; const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#af64eeadabcdf046a7219d024a0d97048">getLibs</a> () const </td></tr>
<tr class="separator:af64eeadabcdf046a7219d024a0d97048"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1cf890a75d1e53f1dfa34ee525a3cd1c"><td class="memItemLeft" align="right" valign="top">std::vector&lt; std::string &gt; const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#a1cf890a75d1e53f1dfa34ee525a3cd1c">getLibDirs</a> () const </td></tr>
<tr class="separator:a1cf890a75d1e53f1dfa34ee525a3cd1c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ace05d08e52d31645a31205dd4b8a94b0"><td class="memItemLeft" align="right" valign="top">std::vector&lt; std::string &gt; const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#ace05d08e52d31645a31205dd4b8a94b0">getExcluded</a> () const </td></tr>
<tr class="separator:ace05d08e52d31645a31205dd4b8a94b0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2cbe193896002017449d5dfd951ad4ad"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php">Config</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#a2cbe193896002017449d5dfd951ad4ad">operator=</a> (<a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php">Config</a> const &amp;c)=delete</td></tr>
<tr class="separator:a2cbe193896002017449d5dfd951ad4ad"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7fc4e01ae1b31975d348fce8a42c156d"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php">Config</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#a7fc4e01ae1b31975d348fce8a42c156d">operator=</a> (<a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php">Config</a> &amp;&amp;c)=delete</td></tr>
<tr class="separator:a7fc4e01ae1b31975d348fce8a42c156d"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-static-methods"></a>
Static Public Member Functions</h2></td></tr>
<tr class="memitem:a96dc985640aaf39350eeeaca0ea0495f"><td class="memItemLeft" align="right" valign="top">static void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#a96dc985640aaf39350eeeaca0ea0495f">setConfigPath</a> (std::string const &amp;configPath)</td></tr>
<tr class="separator:a96dc985640aaf39350eeeaca0ea0495f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a84b2437b12ae2c467c6ffef2c345a808"><td class="memItemLeft" align="right" valign="top">static <a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php">Config</a> const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#a84b2437b12ae2c467c6ffef2c345a808">getConfig</a> ()</td></tr>
<tr class="separator:a84b2437b12ae2c467c6ffef2c345a808"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-static-attribs"></a>
Static Public Attributes</h2></td></tr>
<tr class="memitem:a2417bb5600b882ac654cb1a69b1eb512"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a2417bb5600b882ac654cb1a69b1eb512"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>TAG_COMPILER</b> = &quot;compiler=&quot;</td></tr>
<tr class="separator:a2417bb5600b882ac654cb1a69b1eb512"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af455fab146712ea6808d6c2bcdb6e0a9"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="af455fab146712ea6808d6c2bcdb6e0a9"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>TAG_LINKER</b> = &quot;linker=&quot;</td></tr>
<tr class="separator:af455fab146712ea6808d6c2bcdb6e0a9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab1f4a7cb5a19dcd0f91dda4192b9df3d"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab1f4a7cb5a19dcd0f91dda4192b9df3d"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>TAG_ARCHIVER</b> = &quot;archiver=&quot;</td></tr>
<tr class="separator:ab1f4a7cb5a19dcd0f91dda4192b9df3d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad4a5091b605e8a7a0b4bc356a5d1ad6d"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ad4a5091b605e8a7a0b4bc356a5d1ad6d"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>TAG_CFLAGS</b> = &quot;cflags=&quot;</td></tr>
<tr class="separator:ad4a5091b605e8a7a0b4bc356a5d1ad6d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa8c88a69c1aadd264c366bbbe18d0050"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa8c88a69c1aadd264c366bbbe18d0050"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>TAG_LDFLAGS</b> = &quot;ldflags=&quot;</td></tr>
<tr class="separator:aa8c88a69c1aadd264c366bbbe18d0050"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a892d0547c5bf39498f65b50660bcf758"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a892d0547c5bf39498f65b50660bcf758"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>TAG_INC</b> = &quot;includes=&quot;</td></tr>
<tr class="separator:a892d0547c5bf39498f65b50660bcf758"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a33ea0f243093e372a3a11454aab704ee"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a33ea0f243093e372a3a11454aab704ee"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>TAG_LIB</b> = &quot;lib=&quot;</td></tr>
<tr class="separator:a33ea0f243093e372a3a11454aab704ee"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7b410a7e7c402fad999b2ad010ff0d1b"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a7b410a7e7c402fad999b2ad010ff0d1b"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>TAG_LIBDIR</b> = &quot;libdir=&quot;</td></tr>
<tr class="separator:a7b410a7e7c402fad999b2ad010ff0d1b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a44e868b1b0b2e1a337dd5d1a5cf95361"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a44e868b1b0b2e1a337dd5d1a5cf95361"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>TAG_OUT</b> = &quot;out=&quot;</td></tr>
<tr class="separator:a44e868b1b0b2e1a337dd5d1a5cf95361"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8b51d14dc886222e625e01ee1a0547c8"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a8b51d14dc886222e625e01ee1a0547c8"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>TAG_EXCLUDED</b> = &quot;excluded=&quot;</td></tr>
<tr class="separator:a8b51d14dc886222e625e01ee1a0547c8"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Represent the analyser configuration. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a96e4b7a5d2aac72a5191b7e84cd2fde6"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NREB::Config::Config::Config </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>No default constructor </p>

</div>
</div>
<a class="anchor" id="af208b04fe1dfbf205e56a6615f805d85"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NREB::Config::Config::Config </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php">Config</a> const &amp;&#160;</td>
          <td class="paramname"><em>c</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">c</td><td>the configuration to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a1f2fd0065cb47c13419ceb140c4d3f23"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NREB::Config::Config::Config </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php">Config</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>c</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">c</td><td>the configuration to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a7c4fb34a9348b628431c32339e23aba6"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NREB::Config::Config::~Config </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php" title="Represent the analyser configuration. ">Config</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a69e559ab291bca3247d420044bda1043"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::string const &amp; NREB::Config::Config::getArchiver </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the configuration archiver </dd></dl>

</div>
</div>
<a class="anchor" id="a323be43577c152f4aa1ccb9133f195a1"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::string const &amp; NREB::Config::Config::getCFlags </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the configuration cFlags </dd></dl>

</div>
</div>
<a class="anchor" id="affef9c78e2bca98d8c7cfc6d59b1fad9"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::string const &amp; NREB::Config::Config::getCompiler </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the configuration compiler </dd></dl>

</div>
</div>
<a class="anchor" id="a84b2437b12ae2c467c6ffef2c345a808"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php">Config</a> const &amp; NREB::Config::Config::getConfig </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the configuration instance </dd></dl>

</div>
</div>
<a class="anchor" id="ace05d08e52d31645a31205dd4b8a94b0"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::vector&lt; std::string &gt; const &amp; NREB::Config::Config::getExcluded </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the configuration excluded files </dd></dl>

</div>
</div>
<a class="anchor" id="ab6d531d72529e32002eda38b03130925"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::vector&lt; std::string &gt; const &amp; NREB::Config::Config::getIncludes </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the configuration includes </dd></dl>

</div>
</div>
<a class="anchor" id="ae459ec68a230a671106f926cfd437948"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::string const &amp; NREB::Config::Config::getLdFlags </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the configuration ldFlags </dd></dl>

</div>
</div>
<a class="anchor" id="a1cf890a75d1e53f1dfa34ee525a3cd1c"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::vector&lt; std::string &gt; const &amp; NREB::Config::Config::getLibDirs </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the configuration lib directories </dd></dl>

</div>
</div>
<a class="anchor" id="af64eeadabcdf046a7219d024a0d97048"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::vector&lt; std::string &gt; const &amp; NREB::Config::Config::getLibs </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the configuration libs </dd></dl>

</div>
</div>
<a class="anchor" id="aa48ad93e3e721205c9d6feeffb102eda"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::string const &amp; NREB::Config::Config::getLinker </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the configuration linker </dd></dl>

</div>
</div>
<a class="anchor" id="aee0e564aea1f62a9d1abc9d7e73ce07e"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::string const &amp; NREB::Config::Config::getOut </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the configuration out </dd></dl>

</div>
</div>
<a class="anchor" id="a2cbe193896002017449d5dfd951ad4ad"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php">Config</a>&amp; NREB::Config::Config::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php">Config</a> const &amp;&#160;</td>
          <td class="paramname"><em>c</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">c</td><td>the object to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a7fc4e01ae1b31975d348fce8a42c156d"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php">Config</a>&amp; NREB::Config::Config::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php">Config</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>c</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">c</td><td>the object to move into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a96dc985640aaf39350eeeaca0ea0495f"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NREB::Config::Config::setConfigPath </td>
          <td>(</td>
          <td class="paramtype">std::string const &amp;&#160;</td>
          <td class="paramname"><em>configPath</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Set the configuration file path </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">configPath</td><td>the configuration path </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-Builder/src/Config/<a class="el" href="_n_r_e_b___config_8hpp_source.php">NREB_Config.hpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-Builder/src/Config/<a class="el" href="_n_r_e_b___config_8cpp.php">NREB_Config.cpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
