<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Builder: NREB::IO::File Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="content" id="content">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-12 panel " style="padding-bottom: 15px;">
                                <div style="margin-bottom: 15px;">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e_b.php">NREB</a></li><li class="navelem"><b>IO</b></li><li class="navelem"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_file.php">File</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_b_1_1_i_o_1_1_file-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NREB::IO::File Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Represent a file entry.  
 <a href="class_n_r_e_b_1_1_i_o_1_1_file.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e_b___file_8hpp_source.php">NREB_File.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for NREB::IO::File:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_n_r_e_b_1_1_i_o_1_1_file.png" usemap="#NREB::IO::File_map" alt=""/>
  <map id="NREB::IO::File_map" name="NREB::IO::File_map">
<area href="class_n_r_e_b_1_1_i_o_1_1_entry.php" title="Represent a system entry. " alt="NREB::IO::Entry" shape="rect" coords="0,0,100,24"/>
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a7723d9abedcf87e276a3e85955d87e40"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_file.php#a7723d9abedcf87e276a3e85955d87e40">File</a> (std::string const &amp;n, <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">Entry</a> *p=nullptr)</td></tr>
<tr class="separator:a7723d9abedcf87e276a3e85955d87e40"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae056d8317b104e259ef97fc93e58f37d"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_file.php#ae056d8317b104e259ef97fc93e58f37d">~File</a> ()=default</td></tr>
<tr class="separator:ae056d8317b104e259ef97fc93e58f37d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9b9461e0a9337af21e0fb3d9019025c2"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_file.php#a9b9461e0a9337af21e0fb3d9019025c2">isFile</a> () const override</td></tr>
<tr class="separator:a9b9461e0a9337af21e0fb3d9019025c2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9d0017942f8bf285e71a8399925e2ebd"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_file.php#a9d0017942f8bf285e71a8399925e2ebd">isFolder</a> () const override</td></tr>
<tr class="separator:a9d0017942f8bf285e71a8399925e2ebd"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a06449f6aa77b4a4875ea4fc3abbc5c58"><td class="memItemLeft" align="right" valign="top">std::string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_file.php#a06449f6aa77b4a4875ea4fc3abbc5c58">getObjectName</a> () const </td></tr>
<tr class="separator:a06449f6aa77b4a4875ea4fc3abbc5c58"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a00521e404b437a8046c8fca78754fcb3"><td class="memItemLeft" align="right" valign="top">std::string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_file.php#a00521e404b437a8046c8fca78754fcb3">getObjectPath</a> () const </td></tr>
<tr class="separator:a00521e404b437a8046c8fca78754fcb3"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_class_n_r_e_b_1_1_i_o_1_1_entry"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_class_n_r_e_b_1_1_i_o_1_1_entry')"><img src="closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td></tr>
<tr class="memitem:a7e00f70497859302b2a3b4219a642463 inherit pub_methods_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php#a7e00f70497859302b2a3b4219a642463">Entry</a> (std::string const &amp;n, <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">Entry</a> *p=nullptr)</td></tr>
<tr class="separator:a7e00f70497859302b2a3b4219a642463 inherit pub_methods_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1341296cad92611034593091b988edfa inherit pub_methods_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php#a1341296cad92611034593091b988edfa">~Entry</a> ()=default</td></tr>
<tr class="separator:a1341296cad92611034593091b988edfa inherit pub_methods_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af56ce86fad0cbbbd71a40d91485f0f21 inherit pub_methods_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memItemLeft" align="right" valign="top">std::string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php#af56ce86fad0cbbbd71a40d91485f0f21">getPath</a> () const </td></tr>
<tr class="separator:af56ce86fad0cbbbd71a40d91485f0f21 inherit pub_methods_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9b11eca85c0a8b0753311ccb01ec5f93 inherit pub_methods_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memItemLeft" align="right" valign="top">std::string const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php#a9b11eca85c0a8b0753311ccb01ec5f93">getName</a> () const </td></tr>
<tr class="separator:a9b11eca85c0a8b0753311ccb01ec5f93 inherit pub_methods_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:add028712312b67faee3c3eb55a1002d3 inherit pub_methods_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memItemLeft" align="right" valign="top">const <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">Entry</a> *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php#add028712312b67faee3c3eb55a1002d3">getParent</a> () const </td></tr>
<tr class="separator:add028712312b67faee3c3eb55a1002d3 inherit pub_methods_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="inherited"></a>
Additional Inherited Members</h2></td></tr>
<tr class="inherit_header pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td colspan="2" onclick="javascript:toggleInherit('pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry')"><img src="closed.png" alt="-"/>&#160;Static Public Attributes inherited from <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td></tr>
<tr class="memitem:a9577a0ef9438168326c5765a69b9a806 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a9577a0ef9438168326c5765a69b9a806"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>MARKER_HEADER</b> = &quot;.hpp&quot;</td></tr>
<tr class="separator:a9577a0ef9438168326c5765a69b9a806 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aaa67d74534bc36047eb3331285ada444 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aaa67d74534bc36047eb3331285ada444"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>MARKER_COMPILER</b> = &quot;CXX&quot;</td></tr>
<tr class="separator:aaa67d74534bc36047eb3331285ada444 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2c34c7f0d0e1452735b14efafc1d843a inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a2c34c7f0d0e1452735b14efafc1d843a"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>MARKER_LINKER</b> = &quot;LD&quot;</td></tr>
<tr class="separator:a2c34c7f0d0e1452735b14efafc1d843a inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac2d77e88b9dc3947deb52d4c1c99d189 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac2d77e88b9dc3947deb52d4c1c99d189"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>MARKER_CFLAGS</b> = &quot;CFLAGS&quot;</td></tr>
<tr class="separator:ac2d77e88b9dc3947deb52d4c1c99d189 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5035fce22ffe5f1e4d2ba40a166176cf inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a5035fce22ffe5f1e4d2ba40a166176cf"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>MARKER_LDFLAGS</b> = &quot;LDFLAGS&quot;</td></tr>
<tr class="separator:a5035fce22ffe5f1e4d2ba40a166176cf inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aec59ecdbec428c117d1b571735634a65 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aec59ecdbec428c117d1b571735634a65"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>MARKER_INC</b> = &quot;INC&quot;</td></tr>
<tr class="separator:aec59ecdbec428c117d1b571735634a65 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab55e85d0eed83c60a416496aa48a6547 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab55e85d0eed83c60a416496aa48a6547"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>MARKER_BIN</b> = &quot;BIN&quot;</td></tr>
<tr class="separator:ab55e85d0eed83c60a416496aa48a6547 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a46ae71f0549e0ee9f371eca2192b8195 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a46ae71f0549e0ee9f371eca2192b8195"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>MARKER_LIB</b> = &quot;LIB&quot;</td></tr>
<tr class="separator:a46ae71f0549e0ee9f371eca2192b8195 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acfdf28a70ca8cd130f4823bce3e424ea inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="acfdf28a70ca8cd130f4823bce3e424ea"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>MARKER_LIBDIR</b> = &quot;LIBDIR&quot;</td></tr>
<tr class="separator:acfdf28a70ca8cd130f4823bce3e424ea inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6a3c264b4fdf426c1f66c8b8b0f4153f inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a6a3c264b4fdf426c1f66c8b8b0f4153f"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>MARKER_CHILDS</b> = &quot;childs&quot;</td></tr>
<tr class="separator:a6a3c264b4fdf426c1f66c8b8b0f4153f inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8bc24c0bea5b1525a2fce5638691c472 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a8bc24c0bea5b1525a2fce5638691c472"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>MARKER_OUT</b> = &quot;out&quot;</td></tr>
<tr class="separator:a8bc24c0bea5b1525a2fce5638691c472 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9aab6e21ca0aa75068e7fb5ff93752f1 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a9aab6e21ca0aa75068e7fb5ff93752f1"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>MARKER_TARGET</b> = &quot;all&quot;</td></tr>
<tr class="separator:a9aab6e21ca0aa75068e7fb5ff93752f1 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8fbfeb537444972060cb7404858538fe inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a8fbfeb537444972060cb7404858538fe"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>MARKER_OBJ</b> = &quot;OBJ&quot;</td></tr>
<tr class="separator:a8fbfeb537444972060cb7404858538fe inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad0878242c21353a52474c8950c24bc19 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ad0878242c21353a52474c8950c24bc19"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>MARKER_SOURCE</b> = &quot;.cpp&quot;</td></tr>
<tr class="separator:ad0878242c21353a52474c8950c24bc19 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa00b7c8b862cbef505f2820ad2e781e9 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa00b7c8b862cbef505f2820ad2e781e9"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>MARKER_SOURCE_C</b> = &quot;.c&quot;</td></tr>
<tr class="separator:aa00b7c8b862cbef505f2820ad2e781e9 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a892ceca5de6b4e36f2fd7a9b0c56ceee inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a892ceca5de6b4e36f2fd7a9b0c56ceee"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>MARKER_HEADER_C</b> = &quot;.h&quot;</td></tr>
<tr class="separator:a892ceca5de6b4e36f2fd7a9b0c56ceee inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aad82d8e8b508244e5b3743de6d0efb84 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aad82d8e8b508244e5b3743de6d0efb84"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>MARKER_O</b> = &quot;.o&quot;</td></tr>
<tr class="separator:aad82d8e8b508244e5b3743de6d0efb84 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af5d0e1af9cc6bb3d7751c9e6290a111e inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="af5d0e1af9cc6bb3d7751c9e6290a111e"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>MARKER_OBJDIR</b> = &quot;OBJDIR&quot;</td></tr>
<tr class="separator:af5d0e1af9cc6bb3d7751c9e6290a111e inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1a3e073656fa473553a004fc785c94a1 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a1a3e073656fa473553a004fc785c94a1"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>START_CALL</b> = &quot;$(&quot;</td></tr>
<tr class="separator:a1a3e073656fa473553a004fc785c94a1 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a17cd178a7b2bf60f67cc2c7ebcf6b18f inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a17cd178a7b2bf60f67cc2c7ebcf6b18f"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>END_CALL</b> = &quot;)&quot;</td></tr>
<tr class="separator:a17cd178a7b2bf60f67cc2c7ebcf6b18f inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a400a81a9514e8758e0fe8a9de8f32ddd inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a400a81a9514e8758e0fe8a9de8f32ddd"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>CALL_COMPILER</b> = START_CALL + MARKER_COMPILER + END_CALL</td></tr>
<tr class="separator:a400a81a9514e8758e0fe8a9de8f32ddd inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac98729610fe03b817b599be269e84994 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac98729610fe03b817b599be269e84994"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>CALL_CFLAGS</b> = START_CALL + MARKER_CFLAGS + END_CALL</td></tr>
<tr class="separator:ac98729610fe03b817b599be269e84994 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af7ac5612eb6ce7ac176fd07a4dcfb523 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="af7ac5612eb6ce7ac176fd07a4dcfb523"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>CALL_INC</b> = START_CALL + MARKER_INC + END_CALL</td></tr>
<tr class="separator:af7ac5612eb6ce7ac176fd07a4dcfb523 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae382808e8ca6bcad6d4d22385188afe6 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae382808e8ca6bcad6d4d22385188afe6"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>CALL_OBJDIR</b> = START_CALL + MARKER_OBJDIR + END_CALL</td></tr>
<tr class="separator:ae382808e8ca6bcad6d4d22385188afe6 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:addf8c06f1aa3bb08a0bdc92319224921 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="addf8c06f1aa3bb08a0bdc92319224921"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>CALL_OBJ</b> = START_CALL + MARKER_OBJ + END_CALL</td></tr>
<tr class="separator:addf8c06f1aa3bb08a0bdc92319224921 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aec0ffd465b3490329921711610c5db64 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aec0ffd465b3490329921711610c5db64"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>MAKEFILE</b> = &quot;Makefile&quot;</td></tr>
<tr class="separator:aec0ffd465b3490329921711610c5db64 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a41cda2dd60e1cb4a406dc720d5848926 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a41cda2dd60e1cb4a406dc720d5848926"></a>
static const std::string&#160;</td><td class="memItemRight" valign="bottom"><b>ARCHIVER</b> = &quot;archive.sh&quot;</td></tr>
<tr class="separator:a41cda2dd60e1cb4a406dc720d5848926 inherit pub_static_attribs_class_n_r_e_b_1_1_i_o_1_1_entry"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Represent a file entry. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a7723d9abedcf87e276a3e85955d87e40"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NREB::IO::File::File </td>
          <td>(</td>
          <td class="paramtype">std::string const &amp;&#160;</td>
          <td class="paramname"><em>n</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">Entry</a> *&#160;</td>
          <td class="paramname"><em>p</em> = <code>nullptr</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct an entry </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">n</td><td>the entry's name </td></tr>
    <tr><td class="paramname">p</td><td>the entry's parent </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ae056d8317b104e259ef97fc93e58f37d"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NREB::IO::File::~File </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php" title="Represent a system entry. ">Entry</a> deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a06449f6aa77b4a4875ea4fc3abbc5c58"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::string NREB::IO::File::getObjectName </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the object's file name </dd></dl>

</div>
</div>
<a class="anchor" id="a00521e404b437a8046c8fca78754fcb3"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::string NREB::IO::File::getObjectPath </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the object's file path </dd></dl>

</div>
</div>
<a class="anchor" id="a9b9461e0a9337af21e0fb3d9019025c2"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">bool NREB::IO::File::isFile </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">override</span><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>if the entry is a file </dd></dl>

<p>Implements <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php#aa6f6f349daae620809562993c23603e7">NREB::IO::Entry</a>.</p>

</div>
</div>
<a class="anchor" id="a9d0017942f8bf285e71a8399925e2ebd"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">bool NREB::IO::File::isFolder </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">override</span><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>if the folder is a folder </dd></dl>

<p>Implements <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php#ae1344768dd2c9f6b177a2695de7c0db1">NREB::IO::Entry</a>.</p>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-Builder/src/IO/File/<a class="el" href="_n_r_e_b___file_8hpp_source.php">NREB_File.hpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-Builder/src/IO/File/NREB_File.cpp</li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</div>
</div>
</body>
</html>
