<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Builder: Member List</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e_b.php">NREB</a></li><li class="navelem"><b>IO</b></li><li class="navelem"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">Folder</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NREB::IO::Folder Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">NREB::IO::Folder</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a284ee03f746161b570ecf36f632dce71">analyse</a>()</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">NREB::IO::Folder</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>ARCHIVER</b> (defined in <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a>)</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>CALL_CFLAGS</b> (defined in <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a>)</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>CALL_COMPILER</b> (defined in <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a>)</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>CALL_INC</b> (defined in <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a>)</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>CALL_OBJ</b> (defined in <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a>)</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>CALL_OBJDIR</b> (defined in <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a>)</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#acc66991e9252d115771dc85b615412e0">createArchiverScript</a>(FileList &amp;files) const </td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">NREB::IO::Folder</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a5db1368f10238a5465e81657470baa2a">createMakefile</a>(FileList &amp;files, FolderList &amp;folders, std::string const &amp;src=&quot;src&quot;) const </td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">NREB::IO::Folder</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a2f4e4f205ae80203fe344b249fcc3651">createProjectMakefile</a>(FileList &amp;files, FolderList &amp;folders, std::string const &amp;src=&quot;src&quot;) const </td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">NREB::IO::Folder</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>END_CALL</b> (defined in <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a>)</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php#a7e00f70497859302b2a3b4219a642463">Entry</a>(std::string const &amp;n, Entry *p=nullptr)</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a200d09d5cafa5f42733e0fdab3e6fbfb">Folder</a>(std::string const &amp;n, Entry *p=nullptr)</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">NREB::IO::Folder</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a877992cec520215b8a49c8557ef7e9f0">getBackwardPath</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">NREB::IO::Folder</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a1f91de5890dd9f664b8a15be8797651d">getFolderChild</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">NREB::IO::Folder</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a8b032189a00342609959b3d3b324f211">getHeaderChild</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">NREB::IO::Folder</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php#a9b11eca85c0a8b0753311ccb01ec5f93">getName</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#afef675d6bab5cad8881255604b9cb857">getObjectPath</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">NREB::IO::Folder</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php#add028712312b67faee3c3eb55a1002d3">getParent</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php#af56ce86fad0cbbbd71a40d91485f0f21">getPath</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#ac35d781c5612a55c4e6e60169d4b4a66">getSourceChild</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">NREB::IO::Folder</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#ad2e11edc0714cac960d7737f6769030b">getUpperName</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">NREB::IO::Folder</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#ae8971cd745155563cdb37e259f605caf">hasCHeader</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">NREB::IO::Folder</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a353ff0cc1b8682c152efc6f3fb18a7eb">hasCppHeader</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">NREB::IO::Folder</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a5d2cadc168a1866e66828126d86e9054">hasCppSource</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">NREB::IO::Folder</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a059761302da03e78c01d05e752cf8a50">hasCSource</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">NREB::IO::Folder</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a3c666250bf38cc4924045de654b8a569">hasDeepSources</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">NREB::IO::Folder</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a7ef2443cb0c7accc61a18a225f0ae1a5">hasFileChild</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">NREB::IO::Folder</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#ab169a5723c98e38a28df20b70beabdae">hasFolderChild</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">NREB::IO::Folder</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#abe7407396d7d848325b5d9f9ac870457">insertFileCall</a>(std::ofstream &amp;file) const </td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">NREB::IO::Folder</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#aaa9b103009e579114d6b73afe9cad2e5">insertFileChilds</a>(std::ofstream &amp;file, FileList &amp;files) const </td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">NREB::IO::Folder</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#aeb585ed56b0025aeb6f0eff720db5e1e">insertFolderCalls</a>(std::ofstream &amp;file) const </td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">NREB::IO::Folder</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a4717bec5aa946fe5ac7a0810ef18d9c1">insertFolderChilds</a>(std::ofstream &amp;file, FolderList &amp;folders) const </td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">NREB::IO::Folder</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a94c926fa65e9307bfa0957f17b442613">insertTarget</a>(std::ofstream &amp;file, bool hasFolder, bool hasFile) const </td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">NREB::IO::Folder</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#aa93c5fb7382942b52ac2a4045a963346">isExcluded</a>(std::string const &amp;path)</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">NREB::IO::Folder</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#ac2debe1b29d81be9bd73adbee77aaced">isFile</a>() const override</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">NREB::IO::Folder</a></td><td class="entry"><span class="mlabel">virtual</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a4116a6ce5749b71129dfe45dc7e1598f">isFolder</a>() const override</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">NREB::IO::Folder</a></td><td class="entry"><span class="mlabel">virtual</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>MAKEFILE</b> (defined in <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a>)</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>MARKER_BIN</b> (defined in <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a>)</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>MARKER_CFLAGS</b> (defined in <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a>)</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>MARKER_CHILDS</b> (defined in <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a>)</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>MARKER_COMPILER</b> (defined in <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a>)</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>MARKER_HEADER</b> (defined in <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a>)</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>MARKER_HEADER_C</b> (defined in <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a>)</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>MARKER_INC</b> (defined in <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a>)</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>MARKER_LDFLAGS</b> (defined in <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a>)</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>MARKER_LIB</b> (defined in <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a>)</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>MARKER_LIBDIR</b> (defined in <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a>)</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>MARKER_LINKER</b> (defined in <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a>)</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>MARKER_O</b> (defined in <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a>)</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>MARKER_OBJ</b> (defined in <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a>)</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>MARKER_OBJDIR</b> (defined in <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a>)</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>MARKER_OUT</b> (defined in <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a>)</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>MARKER_SOURCE</b> (defined in <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a>)</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>MARKER_SOURCE_C</b> (defined in <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a>)</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>MARKER_TARGET</b> (defined in <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a>)</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a42b295486bc89df18c9e45301a1368e9">notOnlyHeaders</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">NREB::IO::Folder</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>START_CALL</b> (defined in <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a>)</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php#a1341296cad92611034593091b988edfa">~Entry</a>()=default</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php">NREB::IO::Entry</a></td><td class="entry"><span class="mlabel">virtual</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a11bb19b193b12f799278f26a3bfe941c">~Folder</a>()</td><td class="entry"><a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php">NREB::IO::Folder</a></td><td class="entry"></td></tr>
</table></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
