<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Builder: Class Members - Functions</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="content" id="content">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-12 panel " style="padding-bottom: 15px;">
                                <div style="margin-bottom: 15px;">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li class="current"><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
  <div id="navrow3" class="tabs2">
    <ul class="tablist">
      <li><a href="functions.php"><span>All</span></a></li>
      <li class="current"><a href="functions_func.php"><span>Functions</span></a></li>
    </ul>
  </div>
  <div id="navrow4" class="tabs3">
    <ul class="tablist">
      <li><a href="#index_a"><span>a</span></a></li>
      <li><a href="#index_c"><span>c</span></a></li>
      <li><a href="#index_e"><span>e</span></a></li>
      <li><a href="#index_f"><span>f</span></a></li>
      <li><a href="#index_g"><span>g</span></a></li>
      <li><a href="#index_h"><span>h</span></a></li>
      <li><a href="#index_i"><span>i</span></a></li>
      <li><a href="#index_n"><span>n</span></a></li>
      <li><a href="#index_o"><span>o</span></a></li>
      <li><a href="#index_s"><span>s</span></a></li>
      <li class="current"><a href="#index_0x7e"><span>~</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;

<h3><a class="anchor" id="index_a"></a>- a -</h3><ul>
<li>analyse()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a284ee03f746161b570ecf36f632dce71">NREB::IO::Folder</a>
</li>
</ul>


<h3><a class="anchor" id="index_c"></a>- c -</h3><ul>
<li>Config()
: <a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#a96e4b7a5d2aac72a5191b7e84cd2fde6">NREB::Config::Config</a>
</li>
<li>createArchiverScript()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#acc66991e9252d115771dc85b615412e0">NREB::IO::Folder</a>
</li>
<li>createMakefile()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a5db1368f10238a5465e81657470baa2a">NREB::IO::Folder</a>
</li>
<li>createProjectMakefile()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a2f4e4f205ae80203fe344b249fcc3651">NREB::IO::Folder</a>
</li>
</ul>


<h3><a class="anchor" id="index_e"></a>- e -</h3><ul>
<li>Entry()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php#a7e00f70497859302b2a3b4219a642463">NREB::IO::Entry</a>
</li>
</ul>


<h3><a class="anchor" id="index_f"></a>- f -</h3><ul>
<li>File()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_file.php#a7723d9abedcf87e276a3e85955d87e40">NREB::IO::File</a>
</li>
<li>Folder()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a200d09d5cafa5f42733e0fdab3e6fbfb">NREB::IO::Folder</a>
</li>
</ul>


<h3><a class="anchor" id="index_g"></a>- g -</h3><ul>
<li>getArchiver()
: <a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#a69e559ab291bca3247d420044bda1043">NREB::Config::Config</a>
</li>
<li>getBackwardPath()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a877992cec520215b8a49c8557ef7e9f0">NREB::IO::Folder</a>
</li>
<li>getCFlags()
: <a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#a323be43577c152f4aa1ccb9133f195a1">NREB::Config::Config</a>
</li>
<li>getCompiler()
: <a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#affef9c78e2bca98d8c7cfc6d59b1fad9">NREB::Config::Config</a>
</li>
<li>getConfig()
: <a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#a84b2437b12ae2c467c6ffef2c345a808">NREB::Config::Config</a>
</li>
<li>getExcluded()
: <a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#ace05d08e52d31645a31205dd4b8a94b0">NREB::Config::Config</a>
</li>
<li>getFolderChild()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a1f91de5890dd9f664b8a15be8797651d">NREB::IO::Folder</a>
</li>
<li>getHeaderChild()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a8b032189a00342609959b3d3b324f211">NREB::IO::Folder</a>
</li>
<li>getIncludes()
: <a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#ab6d531d72529e32002eda38b03130925">NREB::Config::Config</a>
</li>
<li>getLdFlags()
: <a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#ae459ec68a230a671106f926cfd437948">NREB::Config::Config</a>
</li>
<li>getLibDirs()
: <a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#a1cf890a75d1e53f1dfa34ee525a3cd1c">NREB::Config::Config</a>
</li>
<li>getLibs()
: <a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#af64eeadabcdf046a7219d024a0d97048">NREB::Config::Config</a>
</li>
<li>getLinker()
: <a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#aa48ad93e3e721205c9d6feeffb102eda">NREB::Config::Config</a>
</li>
<li>getName()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php#a9b11eca85c0a8b0753311ccb01ec5f93">NREB::IO::Entry</a>
</li>
<li>getObjectName()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_file.php#a06449f6aa77b4a4875ea4fc3abbc5c58">NREB::IO::File</a>
</li>
<li>getObjectPath()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_file.php#a00521e404b437a8046c8fca78754fcb3">NREB::IO::File</a>
, <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#afef675d6bab5cad8881255604b9cb857">NREB::IO::Folder</a>
</li>
<li>getOut()
: <a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#aee0e564aea1f62a9d1abc9d7e73ce07e">NREB::Config::Config</a>
</li>
<li>getParent()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php#add028712312b67faee3c3eb55a1002d3">NREB::IO::Entry</a>
</li>
<li>getPath()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php#af56ce86fad0cbbbd71a40d91485f0f21">NREB::IO::Entry</a>
</li>
<li>getSourceChild()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#ac35d781c5612a55c4e6e60169d4b4a66">NREB::IO::Folder</a>
</li>
<li>getUpperName()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#ad2e11edc0714cac960d7737f6769030b">NREB::IO::Folder</a>
</li>
</ul>


<h3><a class="anchor" id="index_h"></a>- h -</h3><ul>
<li>hasCHeader()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#ae8971cd745155563cdb37e259f605caf">NREB::IO::Folder</a>
</li>
<li>hasCppHeader()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a353ff0cc1b8682c152efc6f3fb18a7eb">NREB::IO::Folder</a>
</li>
<li>hasCppSource()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a5d2cadc168a1866e66828126d86e9054">NREB::IO::Folder</a>
</li>
<li>hasCSource()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a059761302da03e78c01d05e752cf8a50">NREB::IO::Folder</a>
</li>
<li>hasDeepSources()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a3c666250bf38cc4924045de654b8a569">NREB::IO::Folder</a>
</li>
<li>hasFileChild()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a7ef2443cb0c7accc61a18a225f0ae1a5">NREB::IO::Folder</a>
</li>
<li>hasFolderChild()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#ab169a5723c98e38a28df20b70beabdae">NREB::IO::Folder</a>
</li>
</ul>


<h3><a class="anchor" id="index_i"></a>- i -</h3><ul>
<li>insertFileCall()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#abe7407396d7d848325b5d9f9ac870457">NREB::IO::Folder</a>
</li>
<li>insertFileChilds()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#aaa9b103009e579114d6b73afe9cad2e5">NREB::IO::Folder</a>
</li>
<li>insertFolderCalls()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#aeb585ed56b0025aeb6f0eff720db5e1e">NREB::IO::Folder</a>
</li>
<li>insertFolderChilds()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a4717bec5aa946fe5ac7a0810ef18d9c1">NREB::IO::Folder</a>
</li>
<li>insertTarget()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a94c926fa65e9307bfa0957f17b442613">NREB::IO::Folder</a>
</li>
<li>isExcluded()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#aa93c5fb7382942b52ac2a4045a963346">NREB::IO::Folder</a>
</li>
<li>isFile()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php#aa6f6f349daae620809562993c23603e7">NREB::IO::Entry</a>
, <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_file.php#a9b9461e0a9337af21e0fb3d9019025c2">NREB::IO::File</a>
, <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#ac2debe1b29d81be9bd73adbee77aaced">NREB::IO::Folder</a>
</li>
<li>isFolder()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php#ae1344768dd2c9f6b177a2695de7c0db1">NREB::IO::Entry</a>
, <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_file.php#a9d0017942f8bf285e71a8399925e2ebd">NREB::IO::File</a>
, <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a4116a6ce5749b71129dfe45dc7e1598f">NREB::IO::Folder</a>
</li>
</ul>


<h3><a class="anchor" id="index_n"></a>- n -</h3><ul>
<li>notOnlyHeaders()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a42b295486bc89df18c9e45301a1368e9">NREB::IO::Folder</a>
</li>
</ul>


<h3><a class="anchor" id="index_o"></a>- o -</h3><ul>
<li>operator=()
: <a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#a2cbe193896002017449d5dfd951ad4ad">NREB::Config::Config</a>
</li>
</ul>


<h3><a class="anchor" id="index_s"></a>- s -</h3><ul>
<li>setConfigPath()
: <a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#a96dc985640aaf39350eeeaca0ea0495f">NREB::Config::Config</a>
</li>
</ul>


<h3><a class="anchor" id="index_0x7e"></a>- ~ -</h3><ul>
<li>~Config()
: <a class="el" href="class_n_r_e_b_1_1_config_1_1_config.php#a7c4fb34a9348b628431c32339e23aba6">NREB::Config::Config</a>
</li>
<li>~Entry()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_entry.php#a1341296cad92611034593091b988edfa">NREB::IO::Entry</a>
</li>
<li>~File()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_file.php#ae056d8317b104e259ef97fc93e58f37d">NREB::IO::File</a>
</li>
<li>~Folder()
: <a class="el" href="class_n_r_e_b_1_1_i_o_1_1_folder.php#a11bb19b193b12f799278f26a3bfe941c">NREB::IO::Folder</a>
</li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</div>
</div>
</body>
</html>
