<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Builder: NRE-Builder</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li class="current"><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">NRE-Builder </div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><p>NRE-Builder is an automatic makefile generator ! It's allowing to create and manage C/C++ project easily :</p>
<h2>Features</h2>
<h3>Project creation</h3>
<p>__./NRE-Builder.exe -c__ __./NRE-Builder.exe -create__ The project will create a base project architecture :</p><ul>
<li>_**bin**_ : Will be used to store compiled binaries</li>
<li>_**lib**_ : Will be used to store static libraries</li>
<li>_**obj**_ : Will be used to store .o files</li>
<li>_**src**_ : Will be used to store sources files, this folder will be analysed by the builder</li>
<li>_**docs**_ : Will be used to store project's documentation</li>
<li>_**uml**_ : Will be used to store UML diagram</li>
<li>_**test**_ : Will be used to store test sources files</li>
<li>_**src/main.cpp**_ : An empty file After the creation the builder will analyse automatically the src directory to create corresponding makefile</li>
</ul>
<h3>Makefile &amp; Libraries generation</h3>
<p>__./NRE-Builder.exe__ __./NRE-Builder.exe -a__ __./NRE-Builder.exe -analyse__ __./NRE-Builder.exe -t__ __./NRE-Builder.exe -test__ The project will analyse the src directory and create all needed makefile. Some makefile can be useless for directory with only header files The builder will search for sub-directory recursively, no need to pack all files in one folder For the builder to correctly analyse the project you need to configurate it correctly :</p><ul>
<li>The config.nre file need to be on the same level as the builder</li>
<li>You need to fill compiler/linker/archiver/out fields</li>
<li>Other fields aren't mandatory :<ul>
<li>_**compiler**_ : You need to specify the compiler to use</li>
<li>_**linker**_ : You need to specify the linker to use</li>
<li>_**archiver**_ : You need to specify the archiver to use</li>
<li>_**cflags**_ : Flags used for compilation</li>
<li>_**ldflags**_ : Flags used for linking</li>
<li>_**includes**_ : Includes for the project, only path separated by a whitespace</li>
<li>_**lib**_ : Library for the project, same format as includes</li>
<li>_**libdir**_ : Library directories for the project, same format as includes</li>
<li>_**out**_ : The out binaries name</li>
<li>_**excluded**_ : Path or word (separated by a whitespace) excluded from the build, every file contaning one of this word/path will be excluded from makefile generation</li>
</ul>
</li>
</ul>
<p>When analysing the tool will create also an archive generation script. A simple bash script to create a static library in the lib directory</p><ul>
<li>With the following name format : Y/libX.a</li>
<li>Where Y is the configuration out path and X the configuration out name</li>
<li>It will regroup every object file (except those excluded from the build)</li>
</ul>
<p>If the test option is specified and not the analyse one, the analyser will look at the test directory and do the same work It will use config.test.nre configuration file. No archive script are generated with this option.</p>
<h3>Multiple Configuration</h3>
<p>__./NRE-Builder.exe -a -s=XXX__ __./NRE-Builder.exe -a -switch=XXX__ __./NRE-Builder.exe -t -s=XXX__ __./NRE-Builder.exe -t -switch=XXX__ The project will no longer search for config.nre file, instead it will search for config.XXX.nre. Allowing you to have multiple configuration easily. If the test option is specified then the tool will search for config.test.XXX.nre. </p>
</div></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
